spring:
  application:
    name: manatal-migration

  profiles:
    active: dev

  batch:
    job:
      enabled: false

migration:
  manatal:
    source:
      token: ${MANATAL_TOKEN:}
    target:
      token: ${MANATAL_TARGET_TOKEN:}
    base-url: https://api.manatal.com/open/v3/
    page-size: 100
    rate-limit-retry-seconds: 60

app:
  base-url: http://localhost:8080

